apiVersion: v1
kind: Service
metadata:
  name: go-grpc-api-gateway
spec:
  selector:
    app: go-grpc-api-gateway
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-grpc-api-gateway
spec:
  selector:
    matchLabels:
      app: go-grpc-api-gateway
  template:
    metadata:
      labels:
        app: go-grpc-api-gateway
    spec:
      containers:
      - name: go-grpc-api-gateway
        image: docker.okidog.xyz/go-grpc-api-gateway
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
        # command: [ "/bin/sh", "-c", "--" ]
        # args: [ "while true; do sleep 30; done;" ]
          
          
        

        
---


# Refer to Makefile  make k8s_configmap

# apiVersion: v1
# kind: apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: go-grpc-frontend-config
# data:
#   key: value
